### ISSUE TITLE
stk500v2 programmer support.

### ISSUE THREAD

**Issue by nroff-man** [sergev/pic32prog#1]
Hi.

I have written a STK500v2 compatible programmer for PIC32MX.

pic32prog currently supports STK500v2 boot loaders only and cannot
work with a programmer.

I have created this patch:
http://hg.kewl.org/pub/nanunanu/file/cc3285bd0fbb/pic32prog/pic32prog-adapter-stk500v2.c.diff

Can you please consider adding programmer support?

Also, do you have any advice about patching pic32prog to support any
baudrate other than 115200 bps? I also need 57600 bps.

Thanks, bye-bye

**Comment by sergev** [comment]
Done: see https://github.com/sergev/pic32prog/commit/833c15f3f9facf63d2e98030645d5cdda6914bee
I tested it on SDZL board - it also has stk500v2 protocol. Seems to work fine.
Thank you!

I'm going to add baudrate option tomorrow.

**Comment by nroff-man** [comment]
hi

There has been a regression and this no longer works.

Last working version seems to be:
"HEAD is now at 905b43e... Update binaries. Fix trailing spaces in the bitbang source files."

pic32prog -d /dev/ttyACM0 mx250.hex
Programmer for Microchip PIC32 microcontrollers, Version 2.0.175
    Copyright: (C) 2011-2015 Serge Vakulenko
      Adapter: STK500v2 Bootloader
 Program area: 1d000000-1d1fffff
    Processor: Bootloader
 Flash memory: 2048 kbytes
  Boot memory: 80 kbytes
         Data: 1480 bytes
        Erase: done
Program flash: #### done
 Program boot: ### done
 Verify flash: ### done
  Verify boot: ## done
 Program rate: 2690 bytes per second

Latest version has this output:

pic32prog -d /dev/ttyACM0 mx250.hex
Programmer for Microchip PIC32 microcontrollers, Version 2.0.189
    Copyright: (C) 2011-2015 Serge Vakulenko
      Adapter: STK500v2 Bootloader
 Program area: 1d000000-1d1fffff
    Processor: Bootloader
 Flash memory: 2048 kbytes
  Boot memory: 80 kbytes
         Data: 1480 bytes
        Erase: done
Program flash: #### done
 Program boot: ### done
 Verify flash: ### done
  Verify boot: #..
error at address 1FC00000: file=3C1A9D00, mem=FF002000

It would seem that pic32prog is sending mangled addresses to the target.

Bye
