### ISSUE TITLE
Compile error for Mac OS X

### ISSUE THREAD

**Issue by rianders** [sergev/pic32prog#11]
```
% make                       
gcc -arch i386 -arch x86_64 -Wall -g -O -Ihidapi -DSVNVERSION='"144"' -DUSE_MPSSE -I/opt/local/include/libusb-legacy   -c -o adapter-pickit2.o adapter-pickit2.c
adapter-pickit2.c:19:10: fatal error: 'usb.h' file not found
#include <usb.h>
         ^
1 error generated.
make: *** [adapter-pickit2.o] Error 1
```

For usb.h I've done the following:
 `brew install libusb`
 `brew install libusb-compat`

In either case I get the compile error.

**Comment by sergev** [comment]
Seems like "brew" installs packages into a different place, not /opt/local. Need to modify Makefile to use a correct path, something like /usr/local/Cellar/libusb/...

I'm afraid, libusb-compat in "brew" is not the libusb-0.1 library which is needed here. Can you please try "port install libusb-legacy" instead?

**Comment by rianders** [comment]
Trying it now.

On Wed, Jul 22, 2015 at 4:07 PM, Serge Vakulenko notifications@github.com
wrote:

> Seems like `brew' installs packages into a different place, not
> /opt/local. Need to modify Makefile to use a correct path, something like
> /usr/local/Cellar/libusb/...
> 
> I'm afraid, libusb-compat in brew' is not the libusb-0.1 library which is
> needed here. Can you please tryport install libusb-legacy' instead?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sergev/pic32prog/issues/11#issuecomment-123847632.

## 

Rick Anderson
Director of Virtual Worlds
Division of Continuing Studies (DoCS)
Rutgers University
(732) 586-3265

**Comment by rianders** [comment]
I did port install libusb-legacy then got the following issue:

```
% make
gcc -arch i386 -arch x86_64 -g -o pic32prog pic32prog.o target.o executive.o hid.o serial.o adapter-pickit2.o adapter-hidboot.o adapter-an1388.o adapter-bitbang.o adapter-stk500v2.o adapter-uhb.o adapter-an1388-uart.o family-mx1.o family-mx3.o family-mz.o adapter-mpsse.o -framework IOKit -framework CoreFoundation /opt/local/lib/libusb-legacy/libusb-legacy.a
ld: warning: ignoring file /opt/local/lib/libusb-legacy/libusb-legacy.a, file was built for archive which is not the architecture being linked (i386): /opt/local/lib/libusb-legacy/libusb-legacy.a
Undefined symbols for architecture i386:
  "_usb_bulk_read", referenced from:
      _mpsse_flush_output in adapter-mpsse.o
  "_usb_bulk_write", referenced from:
      _bulk_write in adapter-mpsse.o
  "_usb_claim_interface", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_close", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
      _mpsse_close in adapter-mpsse.o
  "_usb_control_msg", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_find_busses", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_find_devices", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_get_busses", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_get_string_simple", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_init", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_open", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
  "_usb_release_interface", referenced from:
      _adapter_open_mpsse in adapter-mpsse.o
      _mpsse_close in adapter-mpsse.o
  "_usb_strerror", referenced from:
      _bulk_write in adapter-mpsse.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pic32prog] Error 1
```

**Comment by sergev** [comment]
Oops... pic32prog makefile is configured to build a universal binary (both i386 and x86_64 architectures). Looks like your MacPorts is x86_64 only (probably by default). I would propose to remove "-arch i386" option from CC value in the makefile. It should help to build x86_64-only binary.

**Comment by ricklon** [comment]
OK. I did that it solves the compile problem.
`sudo port install libusb-legacy'

Updated makefile like the following:

```
ifeq ($(UNAME),Darwin)
    CC          +=  -arch x86_64
    LIBS        += -framework IOKit -framework CoreFoundation
    HIDSRC      = hidapi/hid-mac.c
endif
```

 Now it's matching issue #10 and I'm getting the segmentation fault.

```
./pic32prog -d /dev/cu.usbmodem1411 -b 115200 /var/folders/bx/zg7wx2513knbft_4ch_p5m6c0000gp/T/build5361769718787845957.tmp/basicsketch.cpp.hex 
Programmer for Microchip PIC32 microcontrollers, Version 2.0.141
    Copyright: (C) 2011-2015 Serge Vakulenko
      Adapter: STK500v2 Bootloader
 Program area: 1d000000-1d1fffff
zsh: segmentation fault   -d /dev/cu.usbmodem1411 -b 115200 
```

**Comment by sergev** [comment]
I modified the makefile so now it detects available MacPorts architecture automatically: https://github.com/sergev/pic32prog/commit/070a3a3fc3f1b3a0dd0ca102eafb464de5150b09

It works as expected, when I program the RetroBSD kernel to the chipKIT WF32 board:

```
$ pic32prog -d /dev/tty.usbserial-AD01PI3D -b 115200 unix.hex 
Programmer for Microchip PIC32 microcontrollers, Version 2.0.145
    Copyright: (C) 2011-2015 Serge Vakulenko
      Adapter: STK500v2 Bootloader
 Program area: 1d000000-1d1fffff
    Processor: Bootloader
 Flash memory: 2048 kbytes
  Boot memory: 80 kbytes
         Data: 141976 bytes
        Erase: done
Program flash: #################################### done
```

May be it's something in your hex file which causes pic32prog to crash. Can you please e-mail me your basicsketch.cpp.hex file?

**Comment by ricklon** [comment]
Confirmed fixed. Compiling properly now. Uploading properly.

**Comment by sergev** [comment]
Perfect. Thank you for the bug report!
