### ISSUE TITLE
pic32prog fails to open higher numbered COM ports under Windows

### ISSUE THREAD

**Issue by EmbeddedMan** [sergev/pic32prog#12]
I'm using a chipKIT MAX32 board, which regionally enumerated itself as COM11 on my Windows 7 x64 system. When running pic32prog.exe I get this failure:

D:\WinIssueTest>pic32prog.exe -d COM11 -b 115200 WinIssueTest.cpp.hex
Programmer for Microchip PIC32 microcontrollers, Version 2.0.147
    Copyright: (C) 2011-2015 Serge Vakulenko
COM11: Cannot open

No target found.

Now, when I move the same MAX32 board to COM4, I get the following success:

D:\WinIssueTest>pic32prog.exe -d COM4 -b 115200 WinIssueTest.cpp.hex
Programmer for Microchip PIC32 microcontrollers, Version 2.0.147
    Copyright: (C) 2011-2015 Serge Vakulenko
      Adapter: STK500v2 Bootloader
 Program area: 1d000000-1d1fffff
    Processor: Bootloader
 Flash memory: 2048 kbytes
  Boot memory: 80 kbytes
         Data: 25160 bytes
        Erase: done
Program flash: ########################### done
 Verify flash: ########################## done
 Program rate: 2998 bytes per second

Note that when on COM11, I can easily re-program the MAX32 with MPIDE (which uses avrdude), so I know that everything is working fine from the MAX32 end even under COM11, and this is an issue with pic32prog.

*Brian

**Comment by EmbeddedMan** [comment]
After more testing, I've found that pic32prog version 2.0.147 works fine on COM1 through COM9, and fails on any COM port 10 and up.

*Brian

**Comment by EmbeddedMan** [comment]
After reading https://support.microsoft.com/en-us/kb/115831 I have confirmed that using port names like such : "\.\COM256" as the parameter to pic32prog works properly for all COM ports from 1 to 256. This is a workaround for now.

It would be really slick if pic32prog could always add the "\.\" if it is not already present (for Windows) to the com port parameter so that users don't need to know this silly Windows trick.

*Brian

**Comment by EmbeddedMan** [comment]
Note that my previous comment is not appearing correctly because of markdown. You need two back slashes, a period, and then another backslash in front of the COMx part in order for it to work.

*Brian

**Comment by majenkotech** [comment]
pic32prog should parse the COM specification and check the syntax.  If there is no `\\.\` in front then it should add it, and optionally remove a trailing `:` (though I am not sure if that is necessary).  This should of course only be done in the Windows portion of `serial.c` - probably during `serial_open()`.

**Comment by majenkotech** [comment]
![port11](https://cloud.githubusercontent.com/assets/3812892/9023271/436108de-388c-11e5-9cf3-2200e4bf6eee.png)

I have it working.

**Comment by sergev** [comment]
Thank you, Brian, for the bug report.
Thanks Matt for the fix.
I've reworked it a bit to allow arbitrary length of device name: https://github.com/sergev/pic32prog/commit/5783a53fe326689018eb2afa9a292a9df28e11bb
Sorry I cannot test it myself - no Windows computer at hand.

**Comment by majenkotech** [comment]
Works fine on my Windows VM.

**Comment by sergev** [comment]
Perfect! I will update the pic32prog.exe binary.
