### ISSUE TITLE
printf output buffered, is this as intended?

### ISSUE THREAD

**Issue by robert-rozee** [sergev/pic32prog#19]
this a small cosmetic thing, though it has created some confusion - under Linux and OS X, output of progress bars for short events (upload code to NANO, detect adapter) is buffered, so the bar appears only after the full operation is completed.

i see that within main(), there are the following two lines just before the intro message:

```
setvbuf (stdout, (char *)NULL, _IOLBF, 0);
setvbuf (stderr, (char *)NULL, _IOLBF, 0);
```

from the page at http://www.cplusplus.com/reference/cstdio/setvbuf/ it appears that the parameter "_IOLBF" turns **on** line buffering, while the NULL pointer and 0 size allows the OS to create the buffer internally and decide itself on the size.

is this as you intended?

a better option may be "_IONBF", which selects no buffering. this would allow progress bars to display correctly, as well as ensuring that the order of printed output is maintained (at the moment, upon an error occurring, lines get jumbled up between stdout and stderr).

cheers,
rob   :-)

**Comment by sergev** [comment]
Generally, it is assumed that the output is line buffered in the pic32prog. 
There are a few places in the adapter-bitbang.c file when the printf output is not terminated by \n.
In this case it's better to add a call fflush(stdio), which pushes out the buffer.
I will modify the code.

Best wishes,
--Serge

**Comment by sergev** [comment]
Fixed in https://github.com/sergev/pic32prog/commit/a349694f94742e624bd3238df013f9f886c18473
Binaries updated.

**Comment by robert-rozee** [comment]
much appreciate the update. it enables me to do a little more digging into some other (small) things.

i can now confirm that as of a few days ago (version 2.0.174) pic32prog is fully functional under OS X. and, by the way - do comments that i post to a closed issue get sent through to you? i'm still quite low on the GitHub learning curve!

cheers,
rob   :-)

**Comment by sergev** [comment]
Good.
Yes, comments are instantly delivered by e-mail, even for a closed issue. Though I usually cannot react immediately, sorry. It takes time, you know, to switch from other projects, get the sources, recompile, test etc...
