### ISSUE TITLE
Recognize "AVRISP_2" as valid response from chipKIT bootloader

### ISSUE THREAD

**Issue by EmbeddedMan** [sergev/pic32prog#21]
According to the Atmel spec for the STK500 v2 protocol (http://www.atmel.com/Images/doc2591.pdf) "AVRISP_2" is also a valid response to the CMD_SIGN_ON command. pic32prog should treat either string ("STK500_2" or "AVRISP_2") as valid responses.

**Comment by sergev** [comment]
Fixed in https://github.com/sergev/pic32prog/commit/a349694f94742e624bd3238df013f9f886c18473
Binaries updated.
