### ISSUE TITLE
Windows DTR handling needs updating

### ISSUE THREAD

**Issue by EmbeddedMan** [sergev/pic32prog#33]
In the current version (2.0.198) the DTR output is not quite right I think. For boards that use DTR toggling to trigger a reset into bootloader mode (like almost all Digilent chipKIT boards), the desired behavior is the following: When the port is opened, take DTR low, wait about 100mS, then high, and leave it high throughout the rest of the programming. The falling edge of DTR (for these boards) triggers the PIC32 to reset.

I have a fix for this issue, and it will be coming in a PR shortly.

**Comment by EmbeddedMan** [comment]
My mistake - the right thing to do is to assert DTR (lower it) on port open, then deassert it (raise it) on port close, which is exactly what PIC32Prog is doing right now. So there is no need to change anything here.

**Comment by sergev** [comment]
That was my understanding. Basically, chipKIT boards were designed in assumption that the user does not have to do anything special with DTR signal: just open the port (DTR asserted), send the programming data then close the port (DTR deasserted).
