### ISSUE TITLE
Can not program old uC32 and UNO32 boards

### ISSUE THREAD

**Issue by EmbeddedMan** [sergev/pic32prog#34]
The original version of the chipKIT bootloader from Digilent does not support the ERASE ALL command (it does not return any response if you sent it this command) and it does a bulk erase of the chip on the first PROGRAM command. This makes the response from that first program command take between 3.5 and 4 seconds. The current version (2.0.198) of PIC32Prog tries to do an erase (which fails) and if that is commented out, it fails because it's serial timeout is set too short for the response to the first PROGRAM command. This problem can be solved by updating the bootloader on the affected chipKIT boards (which can be done without a hardware programmer by using a bootloader update sketch), but it would be even better if PIC32Prog could work with these older bootloader. (Unfortunately, a large batch of uC32 boards was programmed with this old bootloader, and they will take a while to sell, so this bootloader will be actively going out to users for quite some time yet.)

I have a fix for both of these issues in an upcoming PR.

**Comment by sergev** [comment]
I believe this issue has been fixed in version 2.0.202.

**Comment by EmbeddedMan** [comment]
Confirmed that this issue is now fixed.
