### ISSUE TITLE
Documentation on updating a PICkit3

### ISSUE THREAD

**Issue by cladmi** [sergev/pic32prog#49]
I wrote a documentation to update the PICkit3 on a linux machine using a VM.
Maybe someone is interested to review or just put the link somewhere when it will be merged.

Edit: it is better with the link: https://github.com/RIOT-OS/RIOT/pull/9260

**Comment by cladmi** [comment]
I has been merged and is now available here:

https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/pic32prog/doc.md

**Comment by sergev** [comment]
Thank you, Gaëtan!
I've added your page as: https://github.com/sergev/pic32prog/wiki/Using-PICkit3

**Comment by cladmi** [comment]
Glad you found it useful :)
