### ISSUE TITLE
Question: is it ok to program pic32mz with pickit2?

### ISSUE THREAD

**Issue by igagis** [sergev/pic32prog#63]
Everywhere on the internet they say that `PIC32MZ` can only be programmed with `PICkit3`, but using the `pic32prog` I was able to program `pic32mz` even with `pickit2` and it went smoothly. I didn't even need to upgrade firmware of my `pickit2` (before I could use my `pickit3` I had to upgrade its firmware).

So, the question is, is it ok to use `pickit2` for programming `PIC32MZ`? does it give exactly same result? What is the difference between using `pickit2` and `pickit3`?

**Comment by igagis** [comment]
using it for two days, didn't notice anything strange, so I assume it is OK.

**Comment by sergev** [comment]
Hi Ivan,
PICkit2 works perfectly fine for pic32mz. I use it for many years. The programming protocol is exactly the same for the target microcontroller. The only difference between PICkit2 and PICkit3 is that former has pic16 inside, and latter is based on pic24.
