### ISSUE TITLE
PICKit 5 support

### ISSUE THREAD

**Issue by hinxx** [sergev/pic32prog#72]
Any plans to add support for PICKit5 ?

**Comment by sergev** [comment]
No way. PICkit 5 has a complicated proprietary protocol. It does not seem reasonable to try to decipher it. There are still PICkits 2 available on Ebay or Amazon.

**Comment by hinxx** [comment]
I saw a bunch of those Pickit2/3/3.5 clones on amazon. None mention pic32 part support. Have you ever used such a clone with your sw to work with pic32mz for example?
In my case I would need to use ICSP interface due to the way PCB is designed. Will that work with those clones?

**Comment by hinxx** [comment]
My friend loaned me a PicKIT2 and it is working as expected!
