### ISSUE TITLE
PICkit 3 scripting firmware

### ISSUE THREAD

**Issue by hinxx** [sergev/pic32prog#73]
I bought a pickit3 clone: `Bus 001 Device 011: ID 04d8:900a Microchip Technology, Inc. PICkit3`. When I try using it with the pic32prog I get the following message:

```
$ ./pic32prog
Programmer for Microchip PIC32 microcontrollers, Version 2.0.259
    Copyright: (C) 2011-2015 Serge Vakulenko
Reply 000
Incompatible PICkit3 firmware detected.
Please, upgrade the firmware using PICkit 3 Scripting Tool.

No target found.
```

How to proceed?

FWIW, the device was not yet used with MPLABX or similar tool.

**Comment by sergev** [comment]
Unfortunately, pickit3 by itself cannot be used with pic32prog. Though there is a way to re-flash it and make it compatibly. Please note that reflashing is a one-way ticket. After that you cannot use your pickit3 with MPLABX.

You need to use PICkit 3 Scripting Tool. It can be downloaded here: http://ww1.microchip.com/downloads/en/DeviceDoc/PICkit3_scripting_v03.00beta.zip

**Comment by hinxx** [comment]
Thanks!
